SELECT
        SPN.*
        ,V.VIEWING_DATE
        ,V.TITLE
        ,V.SUBGENRE
        ,V.CAPPED_VIEWING_DURATION
FROM `sdp-sandbox-nowtv-prod.DATAMARTS.VADES` V INNER JOIN `sdp-sandbox-nowtv-int.JWN43.Nuts_Sports_Custs`SPN 
ON V.PROFILE_ID = SPN.PROFILE_ID
  AND V.VIEWING_DATE BETWEEN DATE(SPN.effective_from) AND DATE(SPN.effective_to)
WHERE COUNTRY_CODE = 'UK'
  AND VIEWING_DATE BETWEEN '2023-01-01' AND CURRENT_DATE()
  AND PRODUCT = "SPORTS"
 --- AND VIEWING_SCENARIO = 'LIVE'